"""
Template phân tích doanh thu bán lẻ cho ASM.
Skill: asm-analyst

Usage:
    python analyze_template.py "path/to/sales_data.xlsx"
    python analyze_template.py "data.xlsx" --output "03_Outputs/BaoCao.md"

Lưu ý: Script này là skeleton code, cần điều chỉnh tên cột
       cho phù hợp với format Excel thực tế từ Odoo/POS.
"""

import argparse
import sys
from pathlib import Path

try:
    import pandas as pd
except ImportError:
    print("❌ Cần cài pandas: pip install pandas openpyxl")
    sys.exit(1)


def load_data(filepath):
    """Load Excel/CSV file into DataFrame."""
    path = Path(filepath)
    if not path.exists():
        print(f"❌ Không tìm thấy file: {filepath}")
        sys.exit(1)

    if path.suffix in [".xlsx", ".xls"]:
        df = pd.read_excel(filepath, engine="openpyxl")
    elif path.suffix == ".csv":
        df = pd.read_csv(filepath, encoding="utf-8-sig")
    else:
        print(f"❌ Format không hỗ trợ: {path.suffix}")
        sys.exit(1)

    print(f"📂 Đã đọc: {filepath} ({len(df)} dòng, {len(df.columns)} cột)")
    return df


def clean_data(df):
    """Clean and standardize column names."""
    # Remove leading/trailing whitespace from column names
    df.columns = df.columns.str.strip()

    # Drop completely empty rows
    df = df.dropna(how="all")

    print(f"🧹 Sau khi clean: {len(df)} dòng")
    return df


def analyze_by_store(df, revenue_col="Doanh thu", store_col="Cửa hàng"):
    """Analyze revenue by store."""
    if revenue_col not in df.columns or store_col not in df.columns:
        print(f"⚠️ Không tìm thấy cột '{revenue_col}' hoặc '{store_col}'")
        print(f"   Các cột hiện có: {list(df.columns)}")
        return None

    summary = df.groupby(store_col)[revenue_col].agg(["sum", "mean", "count"])
    summary.columns = ["Tổng DT", "TB/đơn", "Số đơn"]
    summary = summary.sort_values("Tổng DT", ascending=False)

    # Add ranking color
    max_dt = summary["Tổng DT"].max()
    summary["Xếp hạng"] = summary["Tổng DT"].apply(
        lambda x: "🟢" if x >= max_dt * 0.8 else ("🟡" if x >= max_dt * 0.5 else "🔴")
    )

    return summary


def analyze_by_product(df, revenue_col="Doanh thu", product_col="Sản phẩm", qty_col="Số lượng"):
    """Analyze top products by revenue."""
    required = [revenue_col, product_col]
    missing = [c for c in required if c not in df.columns]
    if missing:
        print(f"⚠️ Thiếu cột: {missing}")
        return None

    product_summary = df.groupby(product_col).agg(
        **{
            "Tổng DT": (revenue_col, "sum"),
            "Số đơn": (revenue_col, "count"),
        }
    )

    if qty_col in df.columns:
        qty_summary = df.groupby(product_col)[qty_col].sum()
        product_summary["Tổng SL"] = qty_summary

    product_summary = product_summary.sort_values("Tổng DT", ascending=False)
    return product_summary.head(10)


def generate_markdown_report(store_data, product_data, filepath, output_path=None):
    """Generate a Markdown report."""
    lines = []
    lines.append("# 📊 Báo Cáo Phân Tích Doanh Thu")
    lines.append(f"\n> **Nguồn dữ liệu:** `{filepath}`")
    lines.append(f"> **Ngày tạo:** Auto-generated by asm-analyst\n")
    lines.append("---\n")

    # Store analysis
    if store_data is not None:
        lines.append("## 1. Hiệu Suất Theo Cửa Hàng\n")
        lines.append(store_data.to_markdown())
        lines.append("")

        # Quick insight
        top = store_data.index[0]
        bottom = store_data.index[-1]
        lines.append(f"\n> **Insight:** Cửa hàng **{top}** dẫn đầu. "
                      f"Cửa hàng **{bottom}** cần review lại hiệu suất.\n")

    # Product analysis
    if product_data is not None:
        lines.append("## 2. Top 10 Sản Phẩm\n")
        lines.append(product_data.to_markdown())
        lines.append("")

    # Action items
    lines.append("---\n")
    lines.append("## 🎯 Đề Xuất Hành Động\n")
    lines.append("1. [ ] Review cửa hàng 🔴 — tìm nguyên nhân doanh thu thấp")
    lines.append("2. [ ] Kiểm tra tồn kho Top 3 sản phẩm best-seller")
    lines.append("3. [ ] So sánh với chỉ tiêu tháng để tính % hoàn thành")

    report = "\n".join(lines)

    if output_path:
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(report)
        print(f"✅ Đã xuất báo cáo: {output_path}")
    else:
        print(report)


def main():
    parser = argparse.ArgumentParser(description="Phân tích doanh thu bán lẻ cho ASM")
    parser.add_argument("filepath", help="Đường dẫn file Excel/CSV")
    parser.add_argument("--output", "-o", help="Xuất báo cáo ra file .md")
    parser.add_argument("--revenue-col", default="Doanh thu", help="Tên cột doanh thu")
    parser.add_argument("--store-col", default="Cửa hàng", help="Tên cột cửa hàng")
    parser.add_argument("--product-col", default="Sản phẩm", help="Tên cột sản phẩm")

    args = parser.parse_args()

    # Fix encoding for Windows console
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

    df = load_data(args.filepath)
    df = clean_data(df)

    print("\n📊 Phân tích theo cửa hàng...")
    store_data = analyze_by_store(df, args.revenue_col, args.store_col)

    print("📦 Phân tích theo sản phẩm...")
    product_data = analyze_by_product(df, args.revenue_col, args.product_col)

    generate_markdown_report(store_data, product_data, args.filepath, args.output)


if __name__ == "__main__":
    main()
